### ISSUE TITLE
Library naming

### ISSUE THREAD

**Issue by susilehtola** [openmopac/mopac#12]
MOPAC now generates the library `libmopac_core.so`. Would `libmopac.so` not suffice? Are you intending to split the library into parts?

**Comment by godotalgorithm** [comment]
The main reason for that naming choice is a CMake limitation - the natural way to get the name `libmopac.so` is to have a library build target named `mopac`, which is already the build target name for the executable. There is a way to break the connection between target name and filename, and I can switch to this simpler name imminently as I clean up some other build issues.

**Comment by susilehtola** [comment]
`set_target_properties(mopac_core PROPERTIES OUTPUT_NAME "mopac")`

**Comment by godotalgorithm** [comment]
Fixed by 9405517c5f4e6d7a261a0b2aa88b74240f88458f
