### ISSUE TITLE
GEO_REF="self"0 requires DEBUG

### ISSUE THREAD

**Issue by flatstik** [openmopac/mopac#152]
Using the latest github pull on linux requires 'DEBUG' to run correctly. If the keyword 'DEBUG' is not used, 0 is assumed to be an unknown keyword.

**Comment by godotalgorithm** [comment]
That example is also working for me on both Mac and Linux with the development version. What operating system is this happening on? Are you using CMake to build your executable?

The parsing of keyword arguments in quotes has been adjusted somewhat recently, so this could be a subtle special case that is triggering in a very narrow range of conditions. MOPAC's input parsing is extremely complicated, and I can't efficiently debug a problem unless I can reproduce it and then trace back the problem in GDB or some other debugger.

**Comment by godotalgorithm** [comment]
While I'm not getting the error that you are seeing, the constraint value appended to `GEO_REF` doesn't seem to be parsed correctly in your example when I set it to a value other than zero, so the parsing isn't correct here even when an error isn't reported. Maybe if I fix this, then your error will also go away.

**Comment by flatstik** [comment]
The CMake version is 3.18.4-2+deb11u1

**Comment by godotalgorithm** [comment]
The problems with `GEO_REF` that I was able to reproduce have been resolved by this PR. Can you confirm whether or not your problem has been fixed by this update?

**Comment by flatstik** [comment]
I will on next tuesday!
