### ISSUE TITLE
Smiles/inchi input and PDBQT output

### ISSUE THREAD

**Issue by flatstik** [openmopac/mopac#161]
I would love to see additional feature, where I could just assign `GENERATE="smiles_or_inchi_string_here"` command along with other parameters, such as `PM7 ADD-H OPT GNORM=0.0` so that mopac would generate (and optimize) the molecule on the fly. Maybe this could be piggybacked from openbabel. Also, additional PDBQT-output along with would be nice to have which would retain the partial charges of this. See https://github.com/openbabel/openbabel/issues/2595

Now I am using a script which handles all of this, but I'd like to get rid of the autodocktools and the gasteiger charges completely.

**Comment by flatstik** [comment]
I think the PDBQT-out could be done something like this (untested):

```
subroutine pdbqtout(input_fn, idate, verson, ncomments, all_comments, nbreaks, breaks, natoms, labels, elemnt, txtatm1, q2, coord, ele_pdbqt)
  implicit none
  character(len=80), intent(in) :: input_fn
  character(len=10), intent(in) :: idate, verson
  integer, intent(in) :: ncomments, nbreaks, natoms
  character(len=80), dimension(ncomments), intent(in) :: all_comments
  integer, dimension(nbreaks) :: breaks
  character(len=4), dimension(natoms), intent(in) :: labels
  integer, dimension(natoms) :: txtatm1
  real(kind=8), dimension(natoms) :: q2
  real(kind=8), dimension(3, natoms), intent(in) :: coord
  character(len=4), dimension(natoms), intent(in) :: elemnt
  character(len=4) :: ele_pdbqt
  integer :: i, i1, k, nline
  logical :: ter, ter_ok

  nline = 0
  ter_ok = .true.
  ter = .true.

  open (11, file=input_fn // ".pdbqt", status="replace")
  write (11, '(A80)') 'REMARK   1 File:', trim (input_fn), &
    ' Date:', trim (idate)
  do i = 1, ncomments
    write (11, '(A80)') 'REMARK   2', trim (all_comments(i))
  end do
  write (11, '(A80)') 'REMARK   3 This is a MOPAC-generated file'
  write (11, '(A80)') 'REMARK   3 Version:', trim (verson)
  write (11, '(A80)') 'REMARK   3 '
  do i = 1, nbreaks
    if (breaks(i) /= 0) then
      write (11, '(A80)') 'REMARK   3'// &
        ' Charges were multiplied by 0.5 in break', i, ' geometry'
    end if
  end do

  do i1 = 1, natoms
    i = txtatm1(i1)
    if (i == 199) then
      ele_pdbqt = " H"
    else
      ele_pdbqt = elemnt(i)
    end if

    write (11, '(A6,I5,A4,A1,A3,A4,I2,A3,3F8.3,2F8.3,1X,2F8.3,A2)') &
      "ATOM", i1, " ", trim (ele_pdbqt), "  MOL", i1, "   ", coord(1,i1), &
      coord(2,i1), coord(3,i1), 1.00, 0.00, q2(i), " ", trim (labels(i))

    if (i == nline) then
      ter_ok = .false.
    else if (i == nline + 1) then
      ter_ok = .true.
      nline = i
    else
      if (ter) write (11, '(A6)') "TER"
      ter = .true.
      ter_ok = .true.
      nline = i
    end if

    if (ter_ok) then
      ter = .false.
    else
      write (11, '(A6)') "TER"
      nline = 0
    end if

  end do

  if (nline /= 0) write (11, '(A6)') "TER"

  deallocate (q2, coord)
  return
end subroutine pdbqtout

```

**Comment by godotalgorithm** [comment]
About SMILES/InChi strings: I do not want to support more input options to MOPAC, nor do I want to add new dependencies like OpenBabel, which would be the easiest way to implement such a feature as you say. MOPAC is too monolithic as it is, and workflows should be able to use OpenBabel and MOPAC in separate steps if they need flexible file format conversion - atomistic simulation and molecular file format conversion are very different tasks that should be handled by very different software.

Giving the option to output PDBQT is a reasonable request that I can probably accommodate in a timely manner. Specifically, the PDB format does seem to provide space in columns 67 - 76 for non-standard extensions, which is reasonable place to insert partial charges as per the PDBQT format. While I'm slightly philosophically opposed to jamming even more file format options into MOPAC, this is actually just supporting an existing format (PDB) in a more featureful manner. It provides a convenient way to extract partial charge information, which is often why people are using MOPAC in the first place.

**Comment by flatstik** [comment]
> Giving the option to output PDBQT is a reasonable request that I can probably accommodate in a timely manner. Specifically, the PDB format does seem to provide space in columns 67 - 76 for non-standard extensions, which is reasonable place to insert partial charges as per the PDBQT format. While I'm slightly philosophically opposed to jamming even more file format options into MOPAC, this is actually just supporting an existing format (PDB) in a more featureful manner. It provides a convenient way to extract partial charge information, which is often why people are using MOPAC in the first place.

I would appreciate this very much. I use MOPAC mainly to optimize the geometries of molecules and proteins and use them for docking simulations. The NEB-function is also something I'd like to see as most of my trials with protein TS calculations have been just a waste of time..

**Comment by godotalgorithm** [comment]
The current plan is to support NEB with MOPAC through two external programs: an interface with MDI (still under development) that has its own NEB driver, through the existing interface with QCEngine/QCArchive that can run NEB calculations using [geomeTRIC](https://github.com/leeping/geomeTRIC). Implementing MOPAC's MDI interface is my responsibility right now, and it has been hovering near the top of my list of priorities for a while, and the QCArchive developers have NEB working for internal testing purposes, but I don't think it will be released until the student working on it writes a paper about it.

**Comment by godotalgorithm** [comment]
The PDB output will now include partial charge information in the necessary columns to act as a PDBQT file if you add the PRTCHAR keyword to a job. As far as I can tell from online documentation, the partial charge information is the only difference between a PDB and PDBQT file. If there is other missing information from a proper PDBQT file that MOPAC can provide, then please reopen this Issue and clarify further.

**Comment by flatstik** [comment]
Works like charm! Thank you very much! By the way, does mopac calculate the temperature factors or B-factor (on pdb, columns 61 - 66)?

**Comment by godotalgorithm** [comment]
By default, MOPAC has been using the temperature B-factor columns to feed partial charge information to a GUI (the B-factor is the partial charge x10). This is redundant if the optional columns are being used for partial charge information, so I just zeroed them out in that case. If I can adjust this GUI behavior and if the optional columns don't cause problems with other programs, then I might make this the default PDB output behavior before the next MOPAC version release (i.e. PRTCHAR wouldn't be needed for this behavior).

**Comment by flatstik** [comment]
At least for autodock vina (and other docking programs of the like) the output is just dandy with the exception that I have to remove the headers and the last row (END) from the output. The output is rigid, but simple obabel conversion `obabel -i pdbqt output.pdb -o pdbqt output.pdbqt`  adds the branches correctly. 

PyMOL (2.4.0) does not open the PRTCHAR output of proteins correctly. The resulting pdb needs to be converted (`obabel -i pdbqt intput.pdb -o pdb -O output.pdb`

**Comment by flatstik** [comment]
Yup. And that's perfectly fine. This is something which probably should added to manual.... 

I am, by the way, willing to writing the man-pages and compiling/mainaining the deb-package for of mopac if needed..

**Comment by godotalgorithm** [comment]
Yes, this type of documentation - common workflows needed to interface MOPAC with other software - is exactly what I want in a list of use cases once I start updating [the new MOPAC documentation website](https://openmopac.github.io) again. The website has been dormant for a while, but I will shift my main attention there after 2 more MOPAC releases - an imminent release associated with [the new PM6-ORG model in MOPAC](https://doi.org/10.1007/s00894-023-05695-1), and then a release after I complete the 2 open PRs for new MOPAC interfacing.

I was just informed yesterday by #172 that MOPAC is available on Debian and [many other Linux package managers](https://repology.org/project/mopac/versions).
