### ISSUE TITLE
GEO_REF bias value reading chokes on 2nd character

### ISSUE THREAD

**Issue by zfekete2** [openmopac/mopac#166]
As demonstrated with the attached input/output, the program aborts when called with a value field longer than 1 character
(not included are working runs when 1-char value is accepted).

[Cyclobutadiene_GEO_REF.zip](https://github.com/openmopac/mopac/files/12018368/Cyclobutadiene_GEO_REF.zip)

**Comment by flatstik** [comment]
This has already been fixed in the latest github pull. See https://github.com/openmopac/mopac/issues/152

**Comment by godotalgorithm** [comment]
The development version isn't flagging an error anymore, however it does state that `By default, no restraining force will be used` after reading in the geometry on my development machine (Mac), and it doesn't seem to be recognizing the constraining force in the calculation itself right now. The restraining force seems to be parsed and functioning correctly in the output reported by @flatstik on a Linux machine. I need to fix the source of this discrepancy before this issue can be considered resolved.
