### ISSUE TITLE
BZ Keyword

### ISSUE THREAD

**Issue by kamischi** [openmopac/mopac#168]
**Describe the bug**
The documentation is wrong about the keyword "BZ". It is not a valid keyword. Instead of "BZ", "BRZ" works

**To Reproduce**
Any example file with BZ as keyword is rejected, whereas with BRZ it works.

**Expected behavior**
Besides the wrong keyword, with BRZ mopac works as expected.

**Operating system**
macOS 13 arm, but this should not matter.

**Additional context**
I found the correct keyword by searching the keywords in the source code.

P.S. Is it possible to attach a text file, like an mopac input file? I could not find such a possibility.
P.P.S In my initial report, I falsely stated "BZR" instead of "BRZ". Sorry.

**Comment by flatstik** [comment]
I don't know whether that is actual bug. 
See https://openmopac.github.io/keywords/BZ.html

**Comment by kamischi** [comment]
Sorry, my fault. The keyword needs to be "BRZ" and not "BZR". I'll correct the bug report.
But it definitely is a bug. Whereas the program is called BZ, the keyword for mopac needs to be "BRZ". Obvious source lines are in bz/bz.F90, src/input/wrtkey.F90 and output/writmo.F90:
bz/bz.F90, 
line 81:      is_brz = (keywrd(:3) == "BRZ")
output/writmo.F90, 
line 735:        if (mers(1) /= 0 .and. .not. mozyme .and. index(keywrd, " BRZ") /= 0) then
src/input/wrtkey.F90,
line 880:  if (myword(allkey, " BRZ"))    write (iw, '(" *  BRZ         - Write file <name>.brz for use by program BZ")')

It took me ages to find it out and is at least a severe bug in the documentation.
