### ISSUE TITLE
conda release

### ISSUE THREAD

**Issue by xiki-tempula** [openmopac/mopac#18]
Is it possible to have mopac available in the conda so we can deploy it more easily, please? Thank you.

**Comment by godotalgorithm** [comment]
Yes. We are finalizing a release right now, which will be immediately followed by the availability of stand-alone binary packages, and deployment on conda-forge will be the next development priority after that.

**Comment by xiki-tempula** [comment]
@godotalgorithm Excellent. Thank you.

**Comment by godotalgorithm** [comment]
MOPAC is now available on the conda-forge channel of the conda package manager. Right now, 22.0.2 is the version available on conda-forge. I will usually update the recipe with new version releases, but v22.0.3 failed the conda-forge CI and will probably be skipped. It's probably an issue with changes I've been making to detecting/installing the OpenMP dependency, which is still in a state of flux.
