### ISSUE TITLE
Linux executable fails.

### ISSUE THREAD

**Issue by paulsaxe** [openmopac/mopac#19]
I downloaded the Linux executable from `http://openmopac.net/MOPAC2016_for_Linux_64_bit.zip`

When I run it, it gives errors to the terminal and NaN's in the output:

```(seamm-mopac) [seamm@minime tmp]$ MOPAC2016.exe mopac.dat 
          Sat Mar 12 14:34:24 2022  Job: 'mopac' started successfully

Intel MKL ERROR: Parameter 1 was incorrect on entry to DSYEVD.

Intel MKL ERROR: Parameter 1 was incorrect on entry to DSYEVD.```

An executable from a couple weeks ago works fine.

**Comment by godotalgorithm** [comment]
I've verified the problem with this build, and I suspect that MOPAC was linked against the wrong BLAS/LAPACK MKL interface in this instance. The other Linux builds (`http://openmopac.net/MOPAC2016_for_CentOS-6.zip` and `http://openmopac.net/MOPAC2016_for_CentOS-7.zip`) seem to be working fine and are practically interchangeable with the one you are trying to use. I'll notify Jimmy of this problem, and it should be simple enough for him to fix on his end.

**Comment by godotalgorithm** [comment]
Jimmy fixed the problem.
