### ISSUE TITLE
I want to avoid sorting Cartesian Gradients in QM/MM for communication with external MD.

### ISSUE THREAD

**Issue by by-student-2017** [openmopac/mopac#204]
**Is your feature request related to a problem? Please describe.**

For smoother communication in QMMM, please stop sorting by largest |Gradient|, or write Cartesian Gradients right next to CARTESIAN COORDINATES.

**Describe the solution you'd like**

For smoother communication in QMMM, please stop sorting by largest |Gradient|

**Describe alternatives you've considered**

Or write Cartesian Gradients right next to CARTESIAN COORDINATES.

**Additional context**

**Comment by by-student-2017** [comment]
Sorry for the inconvenience. I will use the keyword AUX output. http://openmopac.net/manual/QMMM.html

**Comment by godotalgorithm** [comment]
No problem. The original MOPAC output file was designed for human readability, not machine readability. The AUX output file format was added much later to accommodate machine readability of MOPAC outputs. If there is any important information that the AUX file is not providing, then I will consider feature requests to add new information to the AUX file.
