### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by susilehtola** [openmopac/MOPAC#3]
I gave a stab at packaging MOPAC for Fedora.

The compile fails in the link phase with
```
/usr/bin/ld: libmopac-all.so: undefined reference to `gemm_cublas_'
```
It looks like the GPU code isn't optional

**Comment by godotalgorithm** [comment]
Are you using the CMake script to compile, or are you doing something else? My best guess at this is that you are compiling all files in the source directory, which includes the "deprecated" directory that isn't part of the active source. The "deprecated" directory includes the old GPU support that doesn't function right now and needs to be updated, which is the only thing I am aware of that would introduce a cuBLAS dependency. I will be removing the "deprecated" folder eventually, and maybe now is a good time to do that to avoid anymore problems like this.

**Comment by godotalgorithm** [comment]
Fixed.
